server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db1?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Fjw20030504
  mail:
    host: smtp.163.com
    username: 19891294013@163.com
    password: DRCJMYFWIGGKGSWM
    port: 465
    properties:
      from: 19891294013@163.com
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
  data:
    redis:
      database: 0
      host: localhost
      port: 6379

